version: '3'

services:
  brevets:
    build: brevets/.
    command: python flask_brevets.py
    ports:
      - "5001:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.5
    ports:
      - "27017:27017"
